route:
  group_by:
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications
receivers:
  - name: email-notifications
    email_configs:
      - to: kaushalkumar5407@gmail.com
        from: Monitoring_Test@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: kaushalkumar5407@gmail.com
        auth_identity: kaushalkumar5407@gmail.com
        auth_password: hbgj pagz lnwy ayph
        send_resolved: true


inhibit_rules:
  - source_match:
      severity: 'critical'            # Source alert severity
    target_match:
      severity: 'warning'             # Target alert severity
    equal: ['alertname', 'dev', 'instance']  # Fields to match

